### ISSUE TITLE
tmp directory not cleaned up after process is run under windows

### ISSUE THREAD

**Issue by GZidar** [arsen/image-optimizer#1]
When the process runs it creates a tmp. directory which because of the dot at the end is an invalid name so it cannot be deleted at the end of the process. The trailing dot occurs because the results.files array contains relative paths that start with dots (eg ./images/file01.png) and this is appended to the ./tmp string to create the temporary directory. 

The fix is to remove the leading dot prior to appending to the ./tmp variable.

This change needs to be made in several places within the image-optimize.js file. The reason I have not submitted this change as a pull request is that I am not in a position to test that the change still functions under Linux (or OSX) so I raised the issue here.

I have attached my altered file (please note that my changes were done in a rush to get the utility to work so I apologise if they are not elegant).

[image-optimize.zip](https://github.com/arsenghazaryan/image-optimizer/files/267354/image-optimize.zip)

Thanks for developing such a handy tool.

**Comment by arsen** [comment]
Hi @GZidar, thank you for reporting this. 
This issue has been fixed by @djromero25.

Thanks.
